//#include <stdio.h>
//#include <string.h>
//int main(){
//	int ab=0,cd=0;
//	FILE *test;
//	test=fopen("testdata.in","r");
//	int a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z;
//	int A,B,C,E,D,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z;
//	char bc[100][100];
//	fscanf(test,"%d\n",&ab);
//	for(int ij=0;ij<ab;ij++){
//	a=b=c=d=e=f=g=h=i=j=k=l=m=n=o=p=q=r=s=t=u=v=w=x=y=z=0;
//	A=B=C=D=E=F=G=H=I=J=K=L=M=N=O=P=Q=R=S=T=U=V=W=X=Y=Z=0;
//	fscanf(test,"%[^\n]\n",&bc[ij]);
//	cd=strlen(bc[ij]);
//		for(int ji=0;ji<cd;ji++){
//		if(bc[ij][ji]=='A'){
//			A++;
//		}
//		if(bc[ij][ji]=='B'){
//			B++;
//		}
//		if(bc[ij][ji]=='C'){
//			C++;
//		}
//		if(bc[ij][ji]=='D'){
//			D++;
//		}
//		if(bc[ij][ji]=='E'){
//			E++;
//		}
//		if(bc[ij][ji]=='F'){
//			F++;
//		}
//		if(bc[ij][ji]=='G'){
//			G++;
//		}
//		if(bc[ij][ji]=='H'){
//			H++;
//		}
//		if(bc[ij][ji]=='I'){
//			I++;
//		}
//		if(bc[ij][ji]=='J'){
//			J++;
//		}
//		if(bc[ij][ji]=='K'){
//			K++;
//		}
//		if(bc[ij][ji]=='L'){
//			L++;
//		}
//		if(bc[ij][ji]=='M'){
//			M++;
//		}
//		if(bc[ij][ji]=='N'){
//			N++;
//		}
//		if(bc[ij][ji]=='O'){
//			O++;
//		}
//		if(bc[ij][ji]=='P'){
//			P++;
//		}
//		if(bc[ij][ji]=='Q'){
//			Q++;
//		}
//		if(bc[ij][ji]=='R'){
//			R++;
//		}
//		if(bc[ij][ji]=='S'){
//			S++;
//		}
//		if(bc[ij][ji]=='T'){
//			T++;
//		}
//		if(bc[ij][ji]=='U'){
//			U++;
//		}
//		if(bc[ij][ji]=='V'){
//			V++;
//		}
//		if(bc[ij][ji]=='W'){
//			W++;
//		}
//		if(bc[ij][ji]=='X'){
//			X++;
//		}
//		if(bc[ij][ji]=='Y'){
//			Y++;
//		}
//		if(bc[ij][ji]=='Z'){
//			Z++;
//		}
//		if(bc[ij][ji]=='a'){
//			a++;
//		}
//		if(bc[ij][ji]=='b'){
//			b++;
//		}
//		if(bc[ij][ji]=='c'){
//			c++;
//		}
//		if(bc[ij][ji]=='d'){
//			d++;
//		}
//		if(bc[ij][ji]=='e'){
//			e++;
//		}
//		if(bc[ij][ji]=='f'){
//			f++;
//		}
//		if(bc[ij][ji]=='g'){
//			g++;
//		}
//		if(bc[ij][ji]=='h'){
//			h++;
//		}
//		if(bc[ij][ji]=='i'){
//			i++;
//		}
//		if(bc[ij][ji]=='j'){
//			j++;
//		}
//		if(bc[ij][ji]=='k'){
//			k++;
//		}
//		if(bc[ij][ji]=='l'){
//			l++;
//		}
//		if(bc[ij][ji]=='m'){
//			m++;
//		}
//		if(bc[ij][ji]=='n'){
//			n++;
//		}
//		if(bc[ij][ji]=='o'){
//			o++;
//		}
//		if(bc[ij][ji]=='p'){
//			p++;
//		}
//		if(bc[ij][ji]=='q'){
//			q++;
//		}
//		if(bc[ij][ji]=='r'){
//			r++;
//		}
//		if(bc[ij][ji]=='s'){
//			s++;
//		}
//		if(bc[ij][ji]=='t'){
//			t++;
//		}
//		if(bc[ij][ji]=='u'){
//			u++;
//		}
//		if(bc[ij][ji]=='v'){
//			v++;
//		}
//		if(bc[ij][ji]=='w'){
//			w++;
//		}
//		if(bc[ij][ji]=='x'){
//			x++;
//		}
//		if(bc[ij][ji]=='y'){
//			y++;
//		}
//		if(bc[ij][ji]=='z'){
//			z++;
//		}
//		}
//		a+=A;
//		b+=B;
//		c+=C;
//		d+=D;
//		e+=E;
//		f+=F;
//		g+=G;
//		h+=H;
//		i+=I;
//		j+=J;
//		k+=K;
//		l+=L;
//		m+=M;
//		n+=N;
//		o+=O;
//		p+=P;
//		q+=Q;
//		r+=R;
//		s+=S;
//		t+=T;
//		u+=U;
//		v+=V;
//		w+=W;
//		x+=X;
//		y+=Y;
//		z+=Z;
//		printf("Case #%d:\n",ij+1);
//		printf("A : %d, B : %d, C : %d, D : %d, E : %d\n",a,b,c,d,e);
//		printf("F : %d, G : %d, H : %d, I : %d, J : %d\n",f,g,h,i,j);
//		printf("K : %d, L : %d, M : %d, N : %d, O : %d\n",k,l,m,n,o);
//		printf("P : %d, Q : %d, R : %d, S : %d, T : %d\n",p,q,r,s,t);
//		printf("U : %d, V : %d, W : %d, X : %d, Y : %d\n",u,v,w,x,y);
//		printf("Z : %d\n\n",z);
//		
//	}
//	
//	
//	return 0;
//}
